SRC =	./main.c\
		./equation_2nd_degres.c\
		./suiteRn.c\
		./goldFibo.c\
		./fibonacci.c\
		./calculFibo.c\
		./421.c\
		421-fonctions.c\


NAME = programme

LIB = -lm ./plots/pbPlots.c ./plots/supportLib.c

compilation:
	gcc ${SRC} -o ${NAME} ${LIB}




	  